[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "folium>=0.19.4",
    "plotly>=6.0.0",
    "streamlit-folium>=0.24.0",
    "streamlit>=1.42.0",
    "faker>=36.1.0",
    "twilio>=9.4.5",
]
